version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "lukaszzychal"
    assignees:
      - "lukaszzychal"

  # Enable version updates for Composer (PHP dependencies)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "lukaszzychal"
    assignees:
      - "lukaszzychal"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "lukaszzychal"
    assignees:
      - "lukaszzychal"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for npm (if any frontend dependencies)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "lukaszzychal"
    assignees:
      - "lukaszzychal"
    commit-message:
      prefix: "chore"
      include: "scope"
